### ISSUE TITLE
Feature Request: automatic block timestamp substitution

### ISSUE THREAD

**Issue by wjmelements** [dapphub/ds-warp#5]
DSWarp is useful for unit-testing time-based events, but it would be even better if 'dapp test' injected DSWarp and substituted instances of 'now' with warp.era() in tested contracts automatically.

**Comment by rainbreak** [comment]
I think this is a bit too magical as it would be modifying source. It's probably fine to do `sed -i 's/now/era()/g' src/*sol`.

I've moved away from using DSWarp, and instead just have an `era()` view function that gets overridden in a test class.
